### PR TITLE
Deleted deprecated QuestionResponse model and removed duplicate line (rank field in Club model)

### PR DESCRIPTION
**Pull request by Porcupine1**

### CODE REVIEW

**Review by aviupadhyayula — APPROVED** [review]
LGTM, good finds.

**Review by rm03 — APPROVED** [review]
lgtm!

**Comment by Porcupine1** [comment]
> LGTM, good finds. Feel free to squash & merge.

I'm not authorized to merge

**Comment by aviupadhyayula** [comment]
> > LGTM, good finds. Feel free to squash & merge.
> 
> I'm not authorized to merge

Looks like you're not a member of the Clubs GH team. I think @rm03's on it, you should get an email when you're added.

**Pull request merged**
