### PR TITLE
Add club rank description algorithm

### PR DESCRIPTION
**Pull request by ezwang**
- Add page describing the current club rank algorithm and links to the page on the FAQ and admissions edit form.
- See [here](https://app.clubhouse.io/pennlabs/story/1264/add-page-describing-club-ranking-system) for the story.

image

### CODE REVIEW

**Comment by davish** [comment]
Just a comment, but maybe calling it "Club Rank" might confuse people? Since they might think it's a definitive ranking of clubs. Instead, something like "Club Recommendation Algorithm" might be better

**Comment by ezwang** [comment]
I like that, I'll change it!

**Comment by cacabo** [comment]
How's it look on mobile?

**Comment by ezwang** [comment]
@cacabo 

image

image

**Comment by valenciafu** [comment]
@cacabo huge block of the checkmark is a bit funky, wanna make it a small in-line on mobile? :D

**Pull request merged**
