### PR TITLE
Make Add Club Button Blue

### PR DESCRIPTION
**Pull request by sigmachirality**
The green on the home page doesn't feel right to me, this makes it the same color as the login button so we maintain visual consistency while also still making the button stand out to the user. Thoughts?

I think we should also change the color of the Edit Club button, or maybe move it under the ellipsis dropdown?

EDIT - @ezwang 

image

### CODE REVIEW

**Comment by valenciafu** [comment]
what do you think about making it clubs blue? create club is definitely not the same level of importance as log in. edit button can be blue too. 

in general, im gonna think more about color-function conventions

**Comment by sigmachirality** [comment]
@valenciafu I'm down to do whatever, just don't like the current green!

**Comment by ezwang** [comment]
@sigmachirality @valenciafu Did we ever come to a consensus for what the color of this button should be?

**Comment by valenciafu** [comment]
@ezwang let's go w clubs blue

**Pull request merged**
