### PR TITLE
Update DLA backend

### PR DESCRIPTION
**Pull request by ArmaanT**
This PR updates the custom django backend to log in users to conform to the [current version provided by DLA](https://github.com/pennlabs/django-labs-accounts/blob/master/accounts/backends.py)

### CODE REVIEW

**Comment by ezwang** [comment]
@ArmaanT would we also need to update the `Pipfile.lock` to use version 0.5.4?

**Comment by ezwang** [comment]
Also is there a way we could abstract out the parts of DLA where clubs backend differs into methods and then override it from clubs? That way when DLA is updated, we don't have to also update the clubs backend.

**Comment by ArmaanT** [comment]
@ezwang I'll have to take another look, but I'm pretty sure that would be possible under the `post_authenticate` function. I can't believe I didn't think about that. I'll try to make the changes tonight.

**Comment by ArmaanT** [comment]
@ezwang After looking at the code, I don't think it would be possible to subclass the DLA backend and modify the `post_authenticate` method. The main issue is we need custom logic to handle the shuffling of usernames to be able to create a user with the correct pennid and pennkey and that can't be done in `post_authenticate`

**Pull request merged**
